// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.0
// source: docs/proto/v1/notification.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListNotificationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnreadOnly    bool                   `protobuf:"varint,1,opt,name=unread_only,json=unreadOnly,proto3" json:"unread_only,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotificationsRequest) Reset() {
	*x = ListNotificationsRequest{}
	mi := &file_docs_proto_v1_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationsRequest) ProtoMessage() {}

func (x *ListNotificationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationsRequest.ProtoReflect.Descriptor instead.
func (*ListNotificationsRequest) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_notification_proto_rawDescGZIP(), []int{0}
}

func (x *ListNotificationsRequest) GetUnreadOnly() bool {
	if x != nil {
		return x.UnreadOnly
	}
	return false
}

func (x *ListNotificationsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListNotificationsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type MarkNotificationReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkNotificationReadRequest) Reset() {
	*x = MarkNotificationReadRequest{}
	mi := &file_docs_proto_v1_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkNotificationReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkNotificationReadRequest) ProtoMessage() {}

func (x *MarkNotificationReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkNotificationReadRequest.ProtoReflect.Descriptor instead.
func (*MarkNotificationReadRequest) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_notification_proto_rawDescGZIP(), []int{1}
}

func (x *MarkNotificationReadRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type NotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	Read          bool                   `protobuf:"varint,7,opt,name=read,proto3" json:"read,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ReadAt        string                 `protobuf:"bytes,9,opt,name=read_at,json=readAt,proto3" json:"read_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationResponse) Reset() {
	*x = NotificationResponse{}
	mi := &file_docs_proto_v1_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationResponse) ProtoMessage() {}

func (x *NotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationResponse.ProtoReflect.Descriptor instead.
func (*NotificationResponse) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_notification_proto_rawDescGZIP(), []int{2}
}

func (x *NotificationResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NotificationResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *NotificationResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *NotificationResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *NotificationResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NotificationResponse) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *NotificationResponse) GetRead() bool {
	if x != nil {
		return x.Read
	}
	return false
}

func (x *NotificationResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *NotificationResponse) GetReadAt() string {
	if x != nil {
		return x.ReadAt
	}
	return ""
}

type ListNotificationsResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Notifications []*NotificationResponse `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
	Total         int32                   `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotificationsResponse) Reset() {
	*x = ListNotificationsResponse{}
	mi := &file_docs_proto_v1_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationsResponse) ProtoMessage() {}

func (x *ListNotificationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationsResponse.ProtoReflect.Descriptor instead.
func (*ListNotificationsResponse) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_notification_proto_rawDescGZIP(), []int{3}
}

func (x *ListNotificationsResponse) GetNotifications() []*NotificationResponse {
	if x != nil {
		return x.Notifications
	}
	return nil
}

func (x *ListNotificationsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_docs_proto_v1_notification_proto protoreflect.FileDescriptor

const file_docs_proto_v1_notification_proto_rawDesc = "" +
	"\n" +
	" docs/proto/v1/notification.proto\x12\agrpc.v1\"i\n" +
	"\x18ListNotificationsRequest\x12\x1f\n" +
	"\vunread_only\x18\x01 \x01(\bR\n" +
	"unreadOnly\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"-\n" +
	"\x1bMarkNotificationReadRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xe2\x01\n" +
	"\x14NotificationResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\atask_id\x18\x03 \x01(\tR\x06taskId\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x06 \x01(\tR\x04body\x12\x12\n" +
	"\x04read\x18\a \x01(\bR\x04read\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x17\n" +
	"\aread_at\x18\t \x01(\tR\x06readAt\"v\n" +
	"\x19ListNotificationsResponse\x12C\n" +
	"\rnotifications\x18\x01 \x03(\v2\x1d.grpc.v1.NotificationResponseR\rnotifications\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total2\xce\x01\n" +
	"\x13NotificationService\x12Z\n" +
	"\x11ListNotifications\x12!.grpc.v1.ListNotificationsRequest\x1a\".grpc.v1.ListNotificationsResponse\x12[\n" +
	"\x14MarkNotificationRead\x12$.grpc.v1.MarkNotificationReadRequest\x1a\x1d.grpc.v1.NotificationResponseB\x0fZ\rdocs/proto/v1b\x06proto3"

var (
	file_docs_proto_v1_notification_proto_rawDescOnce sync.Once
	file_docs_proto_v1_notification_proto_rawDescData []byte
)

func file_docs_proto_v1_notification_proto_rawDescGZIP() []byte {
	file_docs_proto_v1_notification_proto_rawDescOnce.Do(func() {
		file_docs_proto_v1_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_docs_proto_v1_notification_proto_rawDesc), len(file_docs_proto_v1_notification_proto_rawDesc)))
	})
	return file_docs_proto_v1_notification_proto_rawDescData
}

var file_docs_proto_v1_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_docs_proto_v1_notification_proto_goTypes = []any{
	(*ListNotificationsRequest)(nil),    // 0: grpc.v1.ListNotificationsRequest
	(*MarkNotificationReadRequest)(nil), // 1: grpc.v1.MarkNotificationReadRequest
	(*NotificationResponse)(nil),        // 2: grpc.v1.NotificationResponse
	(*ListNotificationsResponse)(nil),   // 3: grpc.v1.ListNotificationsResponse
}
var file_docs_proto_v1_notification_proto_depIdxs = []int32{
	2, // 0: grpc.v1.ListNotificationsResponse.notifications:type_name -> grpc.v1.NotificationResponse
	0, // 1: grpc.v1.NotificationService.ListNotifications:input_type -> grpc.v1.ListNotificationsRequest
	1, // 2: grpc.v1.NotificationService.MarkNotificationRead:input_type -> grpc.v1.MarkNotificationReadRequest
	3, // 3: grpc.v1.NotificationService.ListNotifications:output_type -> grpc.v1.ListNotificationsResponse
	2, // 4: grpc.v1.NotificationService.MarkNotificationRead:output_type -> grpc.v1.NotificationResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_docs_proto_v1_notification_proto_init() }
func file_docs_proto_v1_notification_proto_init() {
	if File_docs_proto_v1_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_docs_proto_v1_notification_proto_rawDesc), len(file_docs_proto_v1_notification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_docs_proto_v1_notification_proto_goTypes,
		DependencyIndexes: file_docs_proto_v1_notification_proto_depIdxs,
		MessageInfos:      file_docs_proto_v1_notification_proto_msgTypes,
	}.Build()
	File_docs_proto_v1_notification_proto = out.File
	file_docs_proto_v1_notification_proto_goTypes = nil
	file_docs_proto_v1_notification_proto_depIdxs = nil
}
