// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Notification struct {
	ID        string
	UserID    string
	TaskID    string
	Type      string
	Title     string
	Body      string
	Read      bool
	CreatedAt time.Time
	ReadAt    *time.Time
}

type Task struct {
	ID          string
	UserID      string
	Title       string
	Description pgtype.Text
	Status      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type User struct {
	ID           string
	Username     string
	Email        string
	PasswordHash string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
