// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package sqlc

import (
	"context"
	"time"
)

const countNotifications = `-- name: CountNotifications :one
SELECT COUNT(*)
FROM notifications
WHERE user_id = $1
  AND (NOT $2::boolean OR read = FALSE)
`

type CountNotificationsParams struct {
	UserID     string
	UnreadOnly bool
}

func (q *Queries) CountNotifications(ctx context.Context, arg CountNotificationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countNotifications, arg.UserID, arg.UnreadOnly)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :exec
INSERT INTO notifications (
    id,
    user_id,
    task_id,
    type,
    title,
    body,
    read,
    created_at,
    read_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
`

type CreateNotificationParams struct {
	ID        string
	UserID    string
	TaskID    string
	Type      string
	Title     string
	Body      string
	Read      bool
	CreatedAt time.Time
	ReadAt    *time.Time
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) error {
	_, err := q.db.Exec(ctx, createNotification,
		arg.ID,
		arg.UserID,
		arg.TaskID,
		arg.Type,
		arg.Title,
		arg.Body,
		arg.Read,
		arg.CreatedAt,
		arg.ReadAt,
	)
	return err
}

const getNotificationByID = `-- name: GetNotificationByID :one
SELECT
    id,
    user_id,
    task_id,
    type,
    title,
    body,
    read,
    created_at,
    read_at
FROM notifications
WHERE id = $1
  AND user_id = $2
`

type GetNotificationByIDParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetNotificationByID(ctx context.Context, arg GetNotificationByIDParams) (Notification, error) {
	row := q.db.QueryRow(ctx, getNotificationByID, arg.ID, arg.UserID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TaskID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.Read,
		&i.CreatedAt,
		&i.ReadAt,
	)
	return i, err
}

const listNotifications = `-- name: ListNotifications :many
SELECT
    id,
    user_id,
    task_id,
    type,
    title,
    body,
    read,
    created_at,
    read_at
FROM notifications
WHERE user_id = $1
  AND (NOT $2::boolean OR read = FALSE)
ORDER BY created_at DESC
LIMIT $4::bigint
OFFSET $3::bigint
`

type ListNotificationsParams struct {
	UserID      string
	UnreadOnly  bool
	OffsetCount int64
	LimitCount  int64
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotifications,
		arg.UserID,
		arg.UnreadOnly,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TaskID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.Read,
			&i.CreatedAt,
			&i.ReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNotification = `-- name: UpdateNotification :execrows
UPDATE notifications
SET
    read = $1,
    read_at = $2
WHERE id = $3
  AND user_id = $4
`

type UpdateNotificationParams struct {
	Read   bool
	ReadAt *time.Time
	ID     string
	UserID string
}

func (q *Queries) UpdateNotification(ctx context.Context, arg UpdateNotificationParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateNotification,
		arg.Read,
		arg.ReadAt,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
