// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTasks = `-- name: CountTasks :one
SELECT COUNT(*)
FROM tasks
WHERE user_id = $1
  AND ($2::text = '' OR status = $2::text)
  AND ($3::text = '' OR title ILIKE '%' || $3::text || '%')
`

type CountTasksParams struct {
	UserID string
	Status string
	Query  string
}

func (q *Queries) CountTasks(ctx context.Context, arg CountTasksParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTasks, arg.UserID, arg.Status, arg.Query)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTask = `-- name: CreateTask :exec
INSERT INTO tasks (
    id,
    user_id,
    title,
    description,
    status,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
`

type CreateTaskParams struct {
	ID          string
	UserID      string
	Title       string
	Description pgtype.Text
	Status      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) error {
	_, err := q.db.Exec(ctx, createTask,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteTask = `-- name: DeleteTask :execrows
DELETE FROM tasks
WHERE id = $1
  AND user_id = $2
`

type DeleteTaskParams struct {
	ID     string
	UserID string
}

func (q *Queries) DeleteTask(ctx context.Context, arg DeleteTaskParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTask, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT
    id,
    user_id,
    title,
    description,
    status,
    created_at,
    updated_at
FROM tasks
WHERE id = $1
  AND user_id = $2
`

type GetTaskByIDParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetTaskByID(ctx context.Context, arg GetTaskByIDParams) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskByID, arg.ID, arg.UserID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTasks = `-- name: ListTasks :many
SELECT
    id,
    user_id,
    title,
    description,
    status,
    created_at,
    updated_at
FROM tasks
WHERE user_id = $1
  AND ($2::text = '' OR status = $2::text)
  AND ($3::text = '' OR title ILIKE '%' || $3::text || '%')
ORDER BY created_at DESC
LIMIT $5::bigint
OFFSET $4::bigint
`

type ListTasksParams struct {
	UserID      string
	Status      string
	Query       string
	OffsetCount int64
	LimitCount  int64
}

func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasks,
		arg.UserID,
		arg.Status,
		arg.Query,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :execrows
UPDATE tasks
SET
    title = $1,
    description = $2,
    status = $3,
    updated_at = $4
WHERE id = $5
  AND user_id = $6
`

type UpdateTaskParams struct {
	Title       string
	Description pgtype.Text
	Status      string
	UpdatedAt   time.Time
	ID          string
	UserID      string
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateTask,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
